## docker-compose para correr rtorrent sobre raspberry
## by PeladoNerd https://youtu.be/pZArt1yEw_o

version: "2.1"

services:

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1002
      - PGID=1002
      - VERSION=docker
      - PLEX_CLAIM=claim-PwJzqxCWW4X4hEzq9Pyr
      - HOSTNAME=plexserver
    #ports:
      #- "32400:32400/tcp"
      #- 33400:33400
    volumes:
      - /home/docker/plex:/root/Library
      - /mnt/storage/downloads:/media
    restart: always
    network_mode: host
  
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ='America/Mexico_City'
    #ports:
      #- "139:139/tcp"
      #- "445:445/tcp"
    network_mode: host
    expose:
      - 445
    volumes:
      - /usr/share/zoneinfo/America/Mexico_City:/etc/localtime
      - /mnt/storage/media:/media
      - /mnt/storage/downloads:/downloads

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1002
      - PGID=1002
      - TZ='America/Mexico_City'
      #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      #- USER=username #optional
      #- PASS=password #optional
      #- WHITELIST=iplist #optional
      #- PEERPORT=peerport #optional
      #- HOST_WHITELIST=dnsname list #optional
    volumes:
      - /mnt/storage/transmission_config:/config
      - /mnt/storage/downloads:/downloads
      #- /path/to/watch/folder:/watch
    #ports:
      #- 9091:9091
      #- 51413:51413
      #- 51413:51413/udp
    expose:
      - 9091
      - 51413
      - 51413/udp
    network_mode: host
    restart: unless-stopped

